services:
  frontend:
    build: ./malhotra_web
    ports:
      - "3000:80"
    restart: unless-stopped

  backend:
    build: ./malhotra_backend
    ports:
      - "5000:5000"
    restart: unless-stopped
    environment:
      - PORT=5000
